### ISSUE TITLE
05. UserStory - Verschiedene Waffen⚔️

### ISSUE THREAD

**Issue by LasseHuhn** [ABI2025/ST1-Shooter-Royal#6]
[Nutzer:in] Als Spieler:in
[Funktion] möchte ich verschiedene Waffen im Spiel benutzen können,
[Wert] um ein abwechslungsreiches Spielerlebnis zu haben.

[DoD] Definition of Done:
Es gibt verschiedene Waffen, die gesammelt und geupgraded werden können. Man kann zwischen verschiedenen Waffen wechseln.

**Comment by gitbyways** [comment]
Jungs, warum ist das bei unseren Issues drin?

**Comment by gitbyways** [comment]
Falsches rep
